name: Rust

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: x86_64_monterey

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --target x86_64-apple-darwin
    - name: Upload the release artifact
      uses: actions/upload-artifact@v4
      with:
        name: mkalias-macOS
        path: target/release/mkalias
    
