name: Rust

on:
  workflow_dispatch

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust toolchain (if needed)
      uses: actions-rs/toolchain@v2
      with:
        toolchain: stable
        target: x86_64-apple-darwin  # 明确指定目标架构为Intel macOS
        override: true
    - name: Build
      run: cargo build --release --target x86_64-apple-darwin
    - name: Upload the release artifact
      uses: actions/upload-artifact@v4
      with:
        name: mkalias-macOS
        path: target/release/mkalias
    
